name: flutter_todo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  realm: ^3.1.0
  path_provider: ^2.0.10
  args: ^2.3.1
  build_cli_annotations: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  build_cli: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/atlas_app/realm_config.json
