name: time_track
description: >-
  A simple command-line time tracking application 
  demonstrating usage of Realm Dart SDK

version: 0.2.0
homepage: https://github.com/realm/realm-dart

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  realm_dart: ^0.10.0+rc
  args: ^2.0.0
  dart_console: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
