name: tasktracker
description: MongoDB flexible sync example.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  realm_dart: ^0.11.0+rc
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
