name: flutter_flexible_sync
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter
  realm: ^1.0.0

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/atlas_app/realm_config.json
