name: provider_shopper
description: A shopping app sample that uses Provider for state management.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  realm: ^0.3.2+beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
