name: provider_shopper
description: A shopping app sample that uses Provider for state management.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  realm: ^0.4.0+beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
